package com.kamis.financemanager.database.specifications;

public enum QueryOperation {
	EQUALS, EQUALS_OBJECT, NOT_EQUALS, NOT_EQUALS_OBJECT, STARTS_WITH, ENDS_WITH, CONTAINS, NOT_CONTAINS, GREATER_THAN,
	GREATER_THAN_EQUAL_TO, LESS_THAN, LESS_THAN_EQUAL_TO, IS_NULL, IS_NOT_NULL, IN, NOT_IN;
}
