FROM eclipse-temurin:latest as builder

WORKDIR /app

COPY .mvn/ .mvn/
COPY mvnw pom.xml ./
RUN ./mvnw dependency:go-offline
COPY ./src ./src
RUN ["./mvnw","-Dmaven.test.skip=true", "clean", "install", "package"] 

FROM eclipse-temurin:latest

RUN groupadd spring 
RUN useradd -g spring spring
USER spring:spring

WORKDIR /app
EXPOSE 8080
COPY --from=builder /app/target/*.jar /app/*.jar
ENTRYPOINT ["java", "-jar", "/app/*.jar"]