spring:
  profiles:
    active: local
  application:
    name: Finance Manager
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        default_schema: FMDB
server:
  port: 8080
  servlet:
    context-path: /api

#Security
jwtSecret: financemanagersecretthatyoushouldoverridewithanenvironmentvar

# generic error messages
genericAccessDeniedErrorMsg: access denied
genericInternalServerErrorMessage: an unexpected error has occured
genericMethodNotAllowedErrorMsg: method not allowed
genericNotFoundErrorMsg: "the requested entity was not found"
genericNotFoundMessage: "resource not found"
requiredFieldsBlankError: "one or more required fields was empty"
userIdRequiredError: "userId is required"
genericSuccessMessage: "operation successful"
effectiveDateRequiredErrorMsg: effective date is required
invalidFrequencyErrorMsg: frequency is missing or invalid
jwtExpiredErrorMsg: Token is expired. Please log in again
genericDeletedMsg: Resource deleted successfully

#Registration Messages
usernameExistsError: "username already exists"
emailExistsError: "email already exists"
invalidPasswordError: "password must contain at least one letter"
userRegisteredMessage: "user registered successfully"

# Loan Messages
invalidLoanPaymentFrequencyError: Valid frequencies for loan payments are monthly, bi-weekly, and weekly
filingTypeRequiredForTaxesError: Filing type is required to calculate taxes on an income

# Income messages
unableToBuildTransactionDaysErrorMsg: Unable to generate transaction days. For bi-weekly frequencies, 'startDate' must be valid. For Monthly or Semi-Monthly frequencies, daysOfMonth must be valid. For Weekly frequencies, 'dayOfWeek'' must be valid. 
unableToFindStandardWithholdingErrorMsg: Unable to locate standard tax withholding information for income
stateTaxCalcMissingErrorMsg: Tax is enabled for user's state but no calculation exists for it
incomeExpiredMsg: Income expired successfully
incomeCreateMsg: Income created successfully

# Transaction Messages
invalidDayOfMonthErrorMsg: invalid transaction dates
invalidAmountErrorMsg: amount is required and must be greater than or equal to 0
atLeastOneDateRequiredErrorMsg: at least one day of the month must be specified for transactions
invalidCategoryErrorMsg: category is missing or invalid
invalidTransactionTypeErrorMsg: type is missing or invalid
transactionCreatedMsg: transaction crated successfully
invalidTransactionSearchCategory: category is invalid
invalidTransactionSearchFrequency: frequency is invalid
invalidTransactionSearchType: type is invalid
invalidTransactionSearchParentName: parentName is invalid

# Auth messages
invalidCredentialsErrorMsg: "invalid credentials"
refreshTokenDoesNotExistErrorMsg: "refresh token is invalid"

# Role constants
defaultUserRole: "user"

# Application details
applicationUsername: financemanager_user1

# Sorting constants
invalidSortTypeErrorMsg: "invalid sortType parameter. valid options are 'asc', and 'desc'"
invalidSortByErrorMsg: invalid sorting option

# Paging constants
invalidPagingParameterErrorMsg: "invalid paging parameters"

# Taxes
paIncomeTaxRate: 0.0307
paUnemploymentTaxRate: 0.0006
