spring:
  profiles:
    active: local
  application:
    name: Finance Manager
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        default_schema: FMDB
server:
  port: 8080
  servlet:
    context-path: /api

#Security
jwtSecret: financemanagersecretthatyoushouldoverridewithanenvironmentvar

# generic error messages
genericAccessDeniedErrorMsg: access denied
genericInternalServerErrorMessage: an unexpected error has occured
genericMethodNotAllowedErrorMsg: method not allowed
genericNotFoundErrorMsg: "the requested entity was not found"
requiredFieldsBlankError: "one or more required fields was empty"
userIdRequiredError: "userId is required"
genericSuccessMessage: "operation successful"

#Registration Messages
usernameExistsError: "username already exists"
emailExistsError: "email already exists"
invalidPasswordError: "password must contain at least one letter"
userRegisteredMessage: "user registered successfully"

# Loan Messages
invalidLoanPaymentFrequencyError: Valid frequencies for loan payments are monthly, bi-weekly, and weekly
invalidLoanSortingOptionsErrorMsg: invalid sorting option. valid options are 'age', 'balance', and 'name'

# Auth messages
invalidCredentialsErrorMsg: "invalid credentials"

# Role constants
defaultUserRole: "user"

# Application details
applicationUsername: financemanager_user1

# Sorting constants
invalidSortTypeErrorMsg: "invalid sortType parameter. valid options are 'asc', and 'desc'"