spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://192.168.1.87:5432/financemanager"
    username: postgres
    password: postgres
  jpa:
    show-sql: true

logging:
  level: 
    com.kamis: DEBUG