spring:
  profiles:
    active: local
  application:
    name: Finance Manager
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        default_schema: FMDB
server:
  port: 8080
  servlet:
    context-path: /api

#Security
jwtSecret: financemanagersecretthatyoushouldoverridewithanenvironmentvar

# Error messages
genericInternalServerErrorMessage: An unexpected error has occured