spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://db:5432/financemanager
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres